spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to the Microservices Banking Loans QA APIs"
  contactDetails:
    name: "P Marnoto - Lead QA"
    email: "pedro@fakemail.com"
  onCallSupport:
    - (212) 555-9764
    - (976) 555-1129