spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to the Microservices Banking Loans Production APIs"
  contactDetails:
    name: "Baddie Bandit - Product Owner"
    email: "baddie@fakemail.com"
  onCallSupport:
    - (212) 555-9764
    - (976) 555-1129